# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geomove.ui'
#
# Created: Fri Jan 18 15:43:02 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Geomove(object):
    def setupUi(self, Geomove):
        Geomove.setObjectName("Geomove")
        Geomove.resize(830, 656)
        self.centralwidget = QtGui.QWidget(Geomove)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainWindowLayout = QtGui.QHBoxLayout()
        self.MainWindowLayout.setSpacing(6)
        self.MainWindowLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.MainWindowLayout.setObjectName("MainWindowLayout")
        self.Data = QtGui.QVBoxLayout()
        self.Data.setObjectName("Data")
        self.AddMap = QtGui.QPushButton(self.centralwidget)
        self.AddMap.setObjectName("AddMap")
        self.Data.addWidget(self.AddMap)
        self.GeoPoints = QtGui.QListWidget(self.centralwidget)
        self.GeoPoints.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.GeoPoints.setObjectName("GeoPoints")
        self.Data.addWidget(self.GeoPoints)
        self.AddPoint = QtGui.QPushButton(self.centralwidget)
        self.AddPoint.setObjectName("AddPoint")
        self.Data.addWidget(self.AddPoint)
        self.Geomaps = QtGui.QListWidget(self.centralwidget)
        self.Geomaps.setObjectName("Geomaps")
        self.Data.addWidget(self.Geomaps)
        self.Data.setStretch(0, 1)
        self.Data.setStretch(1, 1)
        self.Data.setStretch(2, 1)
        self.Data.setStretch(3, 2)
        self.MainWindowLayout.addLayout(self.Data)
        self.MapScreen = QtGui.QVBoxLayout()
        self.MapScreen.setObjectName("MapScreen")
        self.Map = QtGui.QGraphicsView(self.centralwidget)
        self.Map.setObjectName("Map")
        self.MapScreen.addWidget(self.Map)
        self.MainWindowLayout.addLayout(self.MapScreen)
        self.Characteristics = QtGui.QVBoxLayout()
        self.Characteristics.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.Characteristics.setObjectName("Characteristics")
        self.charac = QtGui.QListView(self.centralwidget)
        self.charac.setLineWidth(1)
        self.charac.setObjectName("charac")
        self.Characteristics.addWidget(self.charac)
        self.MainWindowLayout.addLayout(self.Characteristics)
        self.MainWindowLayout.setStretch(0, 2)
        self.MainWindowLayout.setStretch(1, 5)
        self.MainWindowLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.MainWindowLayout)
        Geomove.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(Geomove)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 830, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edition = QtGui.QMenu(self.menuBar)
        self.menu_Edition.setObjectName("menu_Edition")
        self.menu_Settings = QtGui.QMenu(self.menuBar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        Geomove.setMenuBar(self.menuBar)
        self.action_New_Map = QtGui.QAction(Geomove)
        self.action_New_Map.setObjectName("action_New_Map")
        self.action_Open_Map = QtGui.QAction(Geomove)
        self.action_Open_Map.setObjectName("action_Open_Map")
        self.actionOpen_recent_Map = QtGui.QAction(Geomove)
        self.actionOpen_recent_Map.setObjectName("actionOpen_recent_Map")
        self.actionImport_Points = QtGui.QAction(Geomove)
        self.actionImport_Points.setObjectName("actionImport_Points")
        self.actionSave = QtGui.QAction(Geomove)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(Geomove)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtGui.QAction(Geomove)
        self.actionQuit.setObjectName("actionQuit")
        self.actionChange_langugage = QtGui.QAction(Geomove)
        self.actionChange_langugage.setObjectName("actionChange_langugage")
        self.actionImport_points = QtGui.QAction(Geomove)
        self.actionImport_points.setObjectName("actionImport_points")
        self.actionChange_scale = QtGui.QAction(Geomove)
        self.actionChange_scale.setObjectName("actionChange_scale")
        self.menu_File.addAction(self.action_New_Map)
        self.menu_File.addAction(self.action_Open_Map)
        self.menu_File.addAction(self.actionOpen_recent_Map)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Edition.addAction(self.actionImport_points)
        self.menu_Edition.addAction(self.actionChange_scale)
        self.menu_Settings.addAction(self.actionChange_langugage)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Edition.menuAction())
        self.menuBar.addAction(self.menu_Settings.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(Geomove)
        QtCore.QMetaObject.connectSlotsByName(Geomove)

    def retranslateUi(self, Geomove):
        Geomove.setWindowTitle(QtGui.QApplication.translate("Geomove", "Geomove", None, QtGui.QApplication.UnicodeUTF8))
        self.AddMap.setText(QtGui.QApplication.translate("Geomove", "(+)   Add Map", None, QtGui.QApplication.UnicodeUTF8))
        self.AddPoint.setText(QtGui.QApplication.translate("Geomove", "(+)   Add Point", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("Geomove", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edition.setTitle(QtGui.QApplication.translate("Geomove", "&Edition", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("Geomove", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("Geomove", "&Help ?", None, QtGui.QApplication.UnicodeUTF8))
        self.action_New_Map.setText(QtGui.QApplication.translate("Geomove", "&New Map", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_Map.setText(QtGui.QApplication.translate("Geomove", "&Open Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_recent_Map.setText(QtGui.QApplication.translate("Geomove", "Open recent Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Points.setText(QtGui.QApplication.translate("Geomove", "Import Points", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Geomove", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("Geomove", "Save as ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Geomove", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_langugage.setText(QtGui.QApplication.translate("Geomove", "Change langugage", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_points.setText(QtGui.QApplication.translate("Geomove", "Import points", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_scale.setText(QtGui.QApplication.translate("Geomove", "Change scale", None, QtGui.QApplication.UnicodeUTF8))

