# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geomove.ui'
#
# Created: Thu Feb 21 18:38:01 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Geomove(object):
    def setupUi(self, Geomove):
        Geomove.setObjectName("Geomove")
        Geomove.resize(1009, 741)
        self.centralwidget = QtGui.QWidget(Geomove)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainWindowLayout = QtGui.QHBoxLayout()
        self.MainWindowLayout.setSpacing(6)
        self.MainWindowLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.MainWindowLayout.setObjectName("MainWindowLayout")
        self.Data = QtGui.QVBoxLayout()
        self.Data.setObjectName("Data")
        self.addMap = QtGui.QPushButton(self.centralwidget)
        self.addMap.setObjectName("addMap")
        self.Data.addWidget(self.addMap)
        self.listMaps = QtGui.QListView(self.centralwidget)
        self.listMaps.setEnabled(True)
        self.listMaps.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listMaps.setObjectName("listMaps")
        self.Data.addWidget(self.listMaps)
        self.addLocation = QtGui.QPushButton(self.centralwidget)
        self.addLocation.setObjectName("addLocation")
        self.Data.addWidget(self.addLocation)
        self.Filter = QtGui.QVBoxLayout()
        self.Filter.setSpacing(0)
        self.Filter.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.Filter.setObjectName("Filter")
        self.Filtervalues = QtGui.QHBoxLayout()
        self.Filtervalues.setSpacing(3)
        self.Filtervalues.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.Filtervalues.setObjectName("Filtervalues")
        self.agemin = QtGui.QDoubleSpinBox(self.centralwidget)
        self.agemin.setMaximumSize(QtCore.QSize(85, 16777215))
        self.agemin.setPrefix("")
        self.agemin.setMaximum(99.99)
        self.agemin.setSingleStep(0.1)
        self.agemin.setObjectName("agemin")
        self.Filtervalues.addWidget(self.agemin)
        self.Tiret = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.Tiret.setFont(font)
        self.Tiret.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tiret.setTextFormat(QtCore.Qt.AutoText)
        self.Tiret.setWordWrap(False)
        self.Tiret.setMargin(0)
        self.Tiret.setObjectName("Tiret")
        self.Filtervalues.addWidget(self.Tiret)
        self.agemax = QtGui.QDoubleSpinBox(self.centralwidget)
        self.agemax.setMaximumSize(QtCore.QSize(85, 16777215))
        self.agemax.setSingleStep(0.1)
        self.agemax.setProperty("value", 10.0)
        self.agemax.setObjectName("agemax")
        self.Filtervalues.addWidget(self.agemax)
        self.Filtervalues.setStretch(0, 1)
        self.Filtervalues.setStretch(2, 1)
        self.Filter.addLayout(self.Filtervalues)
        self.ConfirmationFilter = QtGui.QPushButton(self.centralwidget)
        self.ConfirmationFilter.setObjectName("ConfirmationFilter")
        self.Filter.addWidget(self.ConfirmationFilter)
        self.Data.addLayout(self.Filter)
        self.listLocations = QtGui.QListView(self.centralwidget)
        self.listLocations.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listLocations.setObjectName("listLocations")
        self.Data.addWidget(self.listLocations)
        self.Zoom = QtGui.QHBoxLayout()
        self.Zoom.setObjectName("Zoom")
        self.Zoomout = QtGui.QPushButton(self.centralwidget)
        self.Zoomout.setObjectName("Zoomout")
        self.Zoom.addWidget(self.Zoomout)
        self.Zoomin = QtGui.QPushButton(self.centralwidget)
        self.Zoomin.setObjectName("Zoomin")
        self.Zoom.addWidget(self.Zoomin)
        self.Data.addLayout(self.Zoom)
        self.Data.setStretch(1, 1)
        self.Data.setStretch(4, 2)
        self.MainWindowLayout.addLayout(self.Data)
        self.MapScreen = QtGui.QVBoxLayout()
        self.MapScreen.setObjectName("MapScreen")
        self.map = QtGui.QGraphicsView(self.centralwidget)
        self.map.setObjectName("map")
        self.MapScreen.addWidget(self.map)
        self.MainWindowLayout.addLayout(self.MapScreen)
        self.Characteristics = QtGui.QVBoxLayout()
        self.Characteristics.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.Characteristics.setObjectName("Characteristics")
        self.characteristics = QtGui.QListView(self.centralwidget)
        self.characteristics.setLineWidth(1)
        self.characteristics.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.characteristics.setSelectionRectVisible(True)
        self.characteristics.setObjectName("characteristics")
        self.Characteristics.addWidget(self.characteristics)
        self.MainWindowLayout.addLayout(self.Characteristics)
        self.MainWindowLayout.setStretch(0, 1)
        self.MainWindowLayout.setStretch(1, 7)
        self.MainWindowLayout.setStretch(2, 2)
        self.horizontalLayout.addLayout(self.MainWindowLayout)
        Geomove.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(Geomove)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1009, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setEnabled(True)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edition = QtGui.QMenu(self.menuBar)
        self.menu_Edition.setObjectName("menu_Edition")
        self.menu_Settings = QtGui.QMenu(self.menuBar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        Geomove.setMenuBar(self.menuBar)
        self.actionNew_Map = QtGui.QAction(Geomove)
        self.actionNew_Map.setObjectName("actionNew_Map")
        self.action_Open_Map = QtGui.QAction(Geomove)
        self.action_Open_Map.setObjectName("action_Open_Map")
        self.actionOpen_recent_Map = QtGui.QAction(Geomove)
        self.actionOpen_recent_Map.setObjectName("actionOpen_recent_Map")
        self.actionSave = QtGui.QAction(Geomove)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(Geomove)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtGui.QAction(Geomove)
        self.actionQuit.setCheckable(False)
        self.actionQuit.setObjectName("actionQuit")
        self.actionChange_language = QtGui.QAction(Geomove)
        self.actionChange_language.setObjectName("actionChange_language")
        self.actionImport_locations = QtGui.QAction(Geomove)
        self.actionImport_locations.setObjectName("actionImport_locations")
        self.actionChange_scale = QtGui.QAction(Geomove)
        self.actionChange_scale.setObjectName("actionChange_scale")
        self.actionVoir_didacticiel = QtGui.QAction(Geomove)
        self.actionVoir_didacticiel.setObjectName("actionVoir_didacticiel")
        self.actionImport_GSL = QtGui.QAction(Geomove)
        self.actionImport_GSL.setObjectName("actionImport_GSL")
        self.menu_File.addAction(self.actionNew_Map)
        self.menu_File.addAction(self.action_Open_Map)
        self.menu_File.addAction(self.actionOpen_recent_Map)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Edition.addAction(self.actionImport_locations)
        self.menu_Edition.addAction(self.actionImport_GSL)
        self.menu_Edition.addAction(self.actionChange_scale)
        self.menu_Settings.addAction(self.actionChange_language)
        self.menu_Help.addAction(self.actionVoir_didacticiel)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Edition.menuAction())
        self.menuBar.addAction(self.menu_Settings.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(Geomove)
        QtCore.QMetaObject.connectSlotsByName(Geomove)

    def retranslateUi(self, Geomove):
        Geomove.setWindowTitle(QtGui.QApplication.translate("Geomove", "Geomove", None, QtGui.QApplication.UnicodeUTF8))
        self.addMap.setText(QtGui.QApplication.translate("Geomove", "(+)   Add Map", None, QtGui.QApplication.UnicodeUTF8))
        self.addLocation.setText(QtGui.QApplication.translate("Geomove", "(+)   Add Location", None, QtGui.QApplication.UnicodeUTF8))
        self.agemin.setSuffix(QtGui.QApplication.translate("Geomove", " mA", None, QtGui.QApplication.UnicodeUTF8))
        self.Tiret.setText(QtGui.QApplication.translate("Geomove", " - ", None, QtGui.QApplication.UnicodeUTF8))
        self.agemax.setSuffix(QtGui.QApplication.translate("Geomove", " mA", None, QtGui.QApplication.UnicodeUTF8))
        self.ConfirmationFilter.setText(QtGui.QApplication.translate("Geomove", "Confirm Locations Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.Zoomout.setText(QtGui.QApplication.translate("Geomove", "Zoom (-)", None, QtGui.QApplication.UnicodeUTF8))
        self.Zoomin.setText(QtGui.QApplication.translate("Geomove", "Zoom (+)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("Geomove", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edition.setTitle(QtGui.QApplication.translate("Geomove", "&Edition", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("Geomove", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("Geomove", "&Help ?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Map.setText(QtGui.QApplication.translate("Geomove", "&New Map", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_Map.setText(QtGui.QApplication.translate("Geomove", "&Open Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_recent_Map.setText(QtGui.QApplication.translate("Geomove", "Open recent Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Geomove", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("Geomove", "Save as ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Geomove", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_language.setText(QtGui.QApplication.translate("Geomove", "Change language", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_locations.setText(QtGui.QApplication.translate("Geomove", "Import Location from Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_scale.setText(QtGui.QApplication.translate("Geomove", "Change scale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVoir_didacticiel.setText(QtGui.QApplication.translate("Geomove", "Watch didacticiel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_GSL.setText(QtGui.QApplication.translate("Geomove", "Import Global Sea Level from Excel", None, QtGui.QApplication.UnicodeUTF8))

