# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geomove.ui'
#
# Created: Wed Jan 30 17:25:40 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Geomove(object):
    def setupUi(self, Geomove):
        Geomove.setObjectName("Geomove")
        Geomove.resize(948, 604)
        self.centralwidget = QtGui.QWidget(Geomove)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainWindowLayout = QtGui.QHBoxLayout()
        self.MainWindowLayout.setSpacing(6)
        self.MainWindowLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.MainWindowLayout.setObjectName("MainWindowLayout")
        self.Data = QtGui.QVBoxLayout()
        self.Data.setObjectName("Data")
        self.addMap = QtGui.QPushButton(self.centralwidget)
        self.addMap.setObjectName("addMap")
        self.Data.addWidget(self.addMap)
        self.listMaps = QtGui.QListView(self.centralwidget)
        self.listMaps.setObjectName("listMaps")
        self.Data.addWidget(self.listMaps)
        self.addLocation = QtGui.QPushButton(self.centralwidget)
        self.addLocation.setObjectName("addLocation")
        self.Data.addWidget(self.addLocation)
        self.listLocations = QtGui.QListView(self.centralwidget)
        self.listLocations.setObjectName("listLocations")
        self.Data.addWidget(self.listLocations)
        self.Data.setStretch(0, 1)
        self.Data.setStretch(2, 1)
        self.MainWindowLayout.addLayout(self.Data)
        self.MapScreen = QtGui.QVBoxLayout()
        self.MapScreen.setObjectName("MapScreen")
        self.map = QtGui.QGraphicsView(self.centralwidget)
        self.map.setObjectName("map")
        self.MapScreen.addWidget(self.map)
        self.MainWindowLayout.addLayout(self.MapScreen)
        self.Characteristics = QtGui.QVBoxLayout()
        self.Characteristics.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.Characteristics.setObjectName("Characteristics")
        self.characteristics = QtGui.QListView(self.centralwidget)
        self.characteristics.setLineWidth(1)
        self.characteristics.setObjectName("characteristics")
        self.Characteristics.addWidget(self.characteristics)
        self.MainWindowLayout.addLayout(self.Characteristics)
        self.MainWindowLayout.setStretch(0, 1)
        self.MainWindowLayout.setStretch(1, 5)
        self.MainWindowLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.MainWindowLayout)
        Geomove.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(Geomove)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 948, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setEnabled(True)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edition = QtGui.QMenu(self.menuBar)
        self.menu_Edition.setObjectName("menu_Edition")
        self.menu_Settings = QtGui.QMenu(self.menuBar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Help = QtGui.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        Geomove.setMenuBar(self.menuBar)
        self.actionNew_Map = QtGui.QAction(Geomove)
        self.actionNew_Map.setObjectName("actionNew_Map")
        self.action_Open_Map = QtGui.QAction(Geomove)
        self.action_Open_Map.setObjectName("action_Open_Map")
        self.actionOpen_recent_Map = QtGui.QAction(Geomove)
        self.actionOpen_recent_Map.setObjectName("actionOpen_recent_Map")
        self.actionImport_Points = QtGui.QAction(Geomove)
        self.actionImport_Points.setObjectName("actionImport_Points")
        self.actionSave = QtGui.QAction(Geomove)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(Geomove)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtGui.QAction(Geomove)
        self.actionQuit.setCheckable(False)
        self.actionQuit.setObjectName("actionQuit")
        self.actionChange_language = QtGui.QAction(Geomove)
        self.actionChange_language.setObjectName("actionChange_language")
        self.actionImport_locations = QtGui.QAction(Geomove)
        self.actionImport_locations.setObjectName("actionImport_locations")
        self.actionChange_scale = QtGui.QAction(Geomove)
        self.actionChange_scale.setObjectName("actionChange_scale")
        self.actionCa_marche_pas = QtGui.QAction(Geomove)
        self.actionCa_marche_pas.setObjectName("actionCa_marche_pas")
        self.actionVoir_didacticiel = QtGui.QAction(Geomove)
        self.actionVoir_didacticiel.setObjectName("actionVoir_didacticiel")
        self.actionCr_dits = QtGui.QAction(Geomove)
        self.actionCr_dits.setObjectName("actionCr_dits")
        self.actionImport_GSL = QtGui.QAction(Geomove)
        self.actionImport_GSL.setObjectName("actionImport_GSL")
        self.menu_File.addAction(self.actionNew_Map)
        self.menu_File.addAction(self.action_Open_Map)
        self.menu_File.addAction(self.actionOpen_recent_Map)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Edition.addAction(self.actionImport_locations)
        self.menu_Edition.addAction(self.actionImport_GSL)
        self.menu_Edition.addAction(self.actionChange_scale)
        self.menu_Settings.addAction(self.actionChange_language)
        self.menu_Help.addAction(self.actionVoir_didacticiel)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Edition.menuAction())
        self.menuBar.addAction(self.menu_Settings.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(Geomove)
        QtCore.QMetaObject.connectSlotsByName(Geomove)

    def retranslateUi(self, Geomove):
        Geomove.setWindowTitle(QtGui.QApplication.translate("Geomove", "Geomove", None, QtGui.QApplication.UnicodeUTF8))
        self.addMap.setText(QtGui.QApplication.translate("Geomove", "(+)   Add Map", None, QtGui.QApplication.UnicodeUTF8))
        self.addLocation.setText(QtGui.QApplication.translate("Geomove", "(+)   Add Location", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("Geomove", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edition.setTitle(QtGui.QApplication.translate("Geomove", "&Edition", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("Geomove", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("Geomove", "&Help ?", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Map.setText(QtGui.QApplication.translate("Geomove", "&New Map", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open_Map.setText(QtGui.QApplication.translate("Geomove", "&Open Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_recent_Map.setText(QtGui.QApplication.translate("Geomove", "Open recent Map", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Points.setText(QtGui.QApplication.translate("Geomove", "Import Points", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Geomove", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("Geomove", "Save as ...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("Geomove", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_language.setText(QtGui.QApplication.translate("Geomove", "Change language", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_locations.setText(QtGui.QApplication.translate("Geomove", "Import Location from Excel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_scale.setText(QtGui.QApplication.translate("Geomove", "Change scale", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCa_marche_pas.setText(QtGui.QApplication.translate("Geomove", "Ca marche pas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVoir_didacticiel.setText(QtGui.QApplication.translate("Geomove", "Watch didacticiel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCr_dits.setText(QtGui.QApplication.translate("Geomove", "Crédits", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_GSL.setText(QtGui.QApplication.translate("Geomove", "Import Global Sea Level from Excel", None, QtGui.QApplication.UnicodeUTF8))

